export const CLASSCODE_ACTIONS = {
	LOAD_CREATE_CLASSCODE: 'LOAD_CREATE_CLASSCODE',
	LOAD_CREATE_CLASSCODE_SUCCESS: 'LOAD_CREATE_CLASSCODE_SUCCESS',
	LOAD_VALIDATE_CLASSCODE: 'LOAD_VALIDATE_CLASSCODE',
	LOAD_VALIDATE_CLASSCODE_SUCCESS: 'LOAD_VALIDATE_CLASSCODE_SUCCESS',
	STOP_LOADING: 'STOP_LOADING',
}
