export const CLASSCODE_ACTIONS = {
	LOAD_CREATE_CLASSCODE: 'LOAD_CREATE_CLASSCODE',
	LOAD_CREATE_CLASSCODE_SUCESS: 'LOAD_CREATE_CLASSCODE_SUCESS',
	LOAD_VALIDATE_CLASSCODE: 'LOAD_VALIDATE_CLASSCODE',
	LOAD_VALIDATE_CLASSCODE_SUCCES: 'LOAD_VALIDATE_CLASSCODE_SUCCES',
	STOP_LOADING: 'STOP_LOADING',
}
