export const COMPANY_ACTIONS = {
	LOAD_COMPANIES_LIST: 'LOAD_COMPANIES_LIST',
	LOAD_COMPANIES_LIST_SUCCESS: 'LOAD_COMPANIES_LIST_SUCCESS',
	LOAD_COMPANY: 'LOAD_COMPANY',
	LOAD_COMPANY_SUCCESS: 'LOAD_COMPANY_SUCCESS',
	STOP_LOADING: 'STOP_LOADING',
}
