export const OBSERVATION_ACTIONS = {
	LOAD_CREATE: 'LOAD_CREATE',
	LOAD_CREATE_SUCCESS: 'LOAD_CREATE_SUCCESS',
	LOAD_CREATE_ERROR: 'LOAD_CREATE_ERROR',
	LOAD_UPDATE: 'LOAD_UPDATE',
	LOAD_UPDATE_SUCCESS: 'LOAD_UPDATE_SUCCESS',
	LOAD_UPDATE_ERROR: 'LOAD_UPDATE_ERROR',
	LOAD_DELETE: 'LOAD_DELETE',
	LOAD_DELETE_SUCCESS: 'LOAD_UPDATE_SUCCESS',
	LOAD_DELETE_ERROR: 'LOAD_UPDATE_ERROR',
	LOAD_OBSERVATIONS_LIST: 'LOAD_OBSERVATIONS_LIST',
	LOAD_OBSERVATIONS_LIST_SUCCESS: 'LOAD_OBSERVATIONS_LIST_SUCCESS',
	LOAD_OBSERVATIONS_LIST_ERROR: 'LOAD_OBSERVATIONS_LIST_ERROR',
}
