export const OBSERVATION_ACTION = {
	LOAD_OBSERVATION: 'LOAD_OBSERVATION',
	LOAD_OBSERVATION_SUCCESS: 'LOAD_OBSERVATION_SUCCESS',
	LOAD_OBSERVATION_ERROR: 'LOAD_OBSERVATION_ERROR',
	LOAD_UPDATE_SUCCESS: 'LOAD_UPDATE_SUCCESS',
	LOAD_UPDATE_ERROR: 'LOAD_UPDATE_ERROR',
	LOAD_DELETE_SUCCESS: 'LOAD_UPDATE_SUCCESS',
	LOAD_DELETE_ERROR: 'LOAD_UPDATE_ERROR',
}
export const OBSERVATIONS_ACTION = {
	LOAD_OBSERVATION: 'LOAD_OBSERVATIONS',
	LOAD_OBSERVATION_SUCCESS: 'LOAD_OBSERVATIONS_SUCCESS',
	LOAD_OBSERVATION_ERROR: 'LOAD_OBSERVATIONS_ERROR',
}
