export const PROPOSAL_ACTIONS = {
	LOAD_LIST_PROPOSALS: 'LOAD_LIST_PROPOSALS',
	LOAD_LIST_PROPOSALS_SUCCESS: 'LOAD_LIST_PROPOSALS_SUCCESS',
	LOAD_LIST_PROPOSALS_ERROR: 'LOAD_LIST_PROPOSALS_ERROR',
	LOAD_PROPOSAL: 'LOAD_PROPOSAL',
	LOAD_PROPOSAL_SUCCESS: 'LOAD_PROPOSAL_SUCCESS',
	LOAD_PROPOSAL_ERROR: 'LOAD_PROPOSAL_ERROR',
}
