export const PUBLICATION_ACTIONS = {
	LOAD_PUBLICATIONS_LIST: 'LOAD_PUBLICATIONS_LIST',
	LOAD_PUBLICATIONS_LIST_SUCCESS: 'LOAD_PUBLICATIONS_LIST_SUCCESS',
	LOAD_DELETE_PUBLICATION_SUCCESS: 'LOAD_DELETE_PUBLICATION_SUCCESS',
	STOP_LOADING: 'STOP_LOADING',
}
