export const PUBLICATION_ACTIONS = {
	LOAD_PUBLICATIONS_LIST: 'LOAD_PUBLICATIONS_LIST',
	LOAD_PUBLICATIONS_LIST_SUCCESS: 'LOAD_PUBLICATIONS_LIST_SUCCESS',
	LOAD_PUBLICATIONS_LIST_ERROR: 'LOAD_PUBLICATIONS_LIST_ERROR',
}
