export const REVIEW_ACTIONS = {
	LOAD_REQUEST: 'LOAD_REQUEST',
	LOAD_CREATE_SUCCESS: 'LOAD_CREATE_SUCCESS',
	LOAD_CREATE_ERROR: 'LOAD_CREATE_ERROR',
	LOAD_GET_SUCCESS: 'LOAD_GET_SUCCESS',
	LOAD_GET_ERROR: 'LOAD_GET_ERROR',
}
