export const REVIEW_ACTIONS = {
	LOAD_REQUEST: 'LOAD_REQUEST',
	LOAD_CREATE_SUCCESS: 'LOAD_CREATE_SUCCESS',
	LOAD_CREATE_ERROR: 'LOAD_CREATE_ERROR',
	LOAD_GET_SUCCESS: 'LOAD_GET_SUCCESS',
	LOAD_GET_ERROR: 'LOAD_GET_ERROR',
	LOAD_UPDATE_SUCCESS: 'LOAD_UPDATE_SUCCESS',
	LOAD_UPDATE_ERROR: 'LOAD_UPDATE_ERROR',
	LOAD_GET_COMPANY_REVIEWS: 'LOAD_GET_COMPANY_REVIEWS',
	LOAD_GET_COMPANY_REVIEWS_SUCCESS: 'LOAD_GET_COMPANY_REVIEWS_SUCCESS',
	STOP_LOADING: 'STOP_LOADING',
}
