export const SPACE_ANSWER_ACTIONS = {
	LOAD_CREATE_SPACE_ANSWER: 'LOAD_CREATE_SPACE_ANSWER',
	LOAD_CREATE_SPACE_ANSWER_SUCCESS: 'LOAD_CREATE_SPACE_ANSWER_SUCCESS',
	LOAD_SPACE_ANSWERS_LIST: 'LOAD_SPACE_ANSWERS_LIST',
	LOAD_SPACE_ANSWERS_LIST_SUCCESS: 'LOAD_SPACE_ANSWERS_LIST_SUCCESS',
	STOP_LOADING: 'STOP_LOADING',
}
