export const SPACE_ACTIONS = {
	LOAD_SPACE: 'LOAD_SPACE',
	LOAD_SPACE_SUCCESS: 'LOAD_SPACE_SUCCESS',
	LOAD_PROJECT_SPACES_SUCCESS: 'LOAD_PROJECT_SPACES_SUCCESS',
	STOP_LOADING: 'STOP_LOADING',
	LOAD_COMPANY_SPACES: 'LOAD_COMPANY_SPACES',
	LOAD_COMPANY_SPACES_SUCCESS: 'LOAD_COMPANY_SPACES_SUCCESS',
}
