exports.API_URL = process.env.REACT_APP_API_URL || 'http://localhost:8080'
exports.BASE_API = process.env.REACT_APP_BASE_API || '/api'
exports.FIREBASE_PROJECT_ID = process.env.REACT_APP_FIREBASE_PROJECT_ID || ''
exports.FIREBASE_APP_ID = process.env.REACT_APP_FIREBASE_APP_ID || ''
exports.FIREBASE_STORAGE_BUCKET =
	process.env.REACT_APP_FIREBASE_STORAGE_BUCKET || ''
exports.FIREBASE_LOCATION_ID = process.env.REACT_APP_FIREBASE_LOCATION_ID || ''
exports.FIREBASE_API_KEY = process.env.REACT_APP_FIREBASE_API_KEY || ''
exports.FIREBASE_AUTH_DOMAIN = process.env.REACT_APP_FIREBASE_AUTH_DOMAIN || ''
exports.FIREBASE_MESSAGING_SENDER_ID =
	process.env.REACT_APP_FIREBASE_MESSAGING_SENDER_ID || ''
exports.FIREBASE_MEASUREMENT_ID =
	process.env.REACT_APP_FIREBASE_MEASUREMENT_ID || ''
